### PR TITLE
Add proto structures and serde tools

### PR DESCRIPTION
**Pull request by keyleu**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: 13 of 37 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`src/shim.rs` line 373 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-NebetZBCrT43JrdbR-9:-NebetZBCrT43JrdbR-A:b700q7d) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/7a24ee0febaf3c7ae5ffdc388a3aa5ba5e6da504/src/shim.rs#L373)):*
> ```XML
>         assert_eq!(coins, cosmwasm_coins);
>     }
> }
> ```

empty line needed
___
*[`src/types/coreum/asset/ft/v1.rs` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-NebfXNw8o-JqWBR6SAa:-NebfXNx4OVABMm3GuHD:begugez) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/7a24ee0febaf3c7ae5ffdc388a3aa5ba5e6da504/src/types/coreum/asset/ft/v1.rs#L1)):*
> ```XML
> use osmosis_std_derive::CosmwasmExt;
> ```

I guess this is generate code. If so a comment should say so and also say that it should not be modified by hand. It is the same for all generate files. 
___
*[`src/types/coreum/asset/ft/v1.rs` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-Nebg0Qm3Hu7pwKTyXDh:-Nebg0Qm3Hu7pwKTyXDi:bkoqnnt) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/7a24ee0febaf3c7ae5ffdc388a3aa5ba5e6da504/src/types/coreum/asset/ft/v1.rs#L2)):*
> ```XML
> use osmosis_std_derive::CosmwasmExt;
> ```

If this is generate code, then instructions should be added as how it was generated. the tools used, how to download and use them.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: 13 of 37 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`src/shim.rs` line 373 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-NebetZBCrT43JrdbR-9:-Nebmvrg5BW9ULIqRbF6:b-7tfmjp) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/7a24ee0febaf3c7ae5ffdc388a3aa5ba5e6da504/src/shim.rs#L373)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

empty line needed
</blockquote></details>

added
___
*[`src/types/coreum/asset/ft/v1.rs` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-NebfXNw8o-JqWBR6SAa:-NebozLbEFlms0rzTIBg:b9flmso) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/7a24ee0febaf3c7ae5ffdc388a3aa5ba5e6da504/src/types/coreum/asset/ft/v1.rs#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I guess this is generate code. If so a comment should say so and also say that it should not be modified by hand. It is the same for all generate files.
</blockquote></details>

Done, added a comment that they should not be modified.
___
*[`src/types/coreum/asset/ft/v1.rs` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-Nebg0Qm3Hu7pwKTyXDh:-Nebp2wsCjpG2hRFOt0e:b6u3era) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/7a24ee0febaf3c7ae5ffdc388a3aa5ba5e6da504/src/types/coreum/asset/ft/v1.rs#L2)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

If this is generate code, then instructions should be added as how it was generated. the tools used, how to download and use them.
</blockquote></details>

Done, added what tools were used, providing link to crate.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: 11 of 37 files reviewed, 4 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`src/shim.rs` line 335 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-NebvIA6AeGQuXwSzFja:-NebvIA6AeGQuXwSzFjb:biakvnq) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/64e7034b7c9f44613a8d714c600e80c0f90c1f33/src/shim.rs#L335)):*
> ```XML
> }
> 
> /// Convert a list of `Coin` from osmosis proto generated proto `Coin` type to cosmwasm `Coin` type
> ```

osmosis ? Same for all palces where we use it.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: 11 of 37 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`src/shim.rs` line 335 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-NebvIA6AeGQuXwSzFja:-NebyK0y9TFGLnk3a2Os:b-ivp9mo) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/64e7034b7c9f44613a8d714c600e80c0f90c1f33/src/shim.rs#L335)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

osmosis ? Same for all palces where we use it.
</blockquote></details>

fixed, was only that comment

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 22 of 37 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`src/types/coreum/asset/ft/v1.rs` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-Nebg0Qm3Hu7pwKTyXDh:-NebxZAw0-aijuRTFkPU:bwpm4v8) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/7a24ee0febaf3c7ae5ffdc388a3aa5ba5e6da504/src/types/coreum/asset/ft/v1.rs#L2)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Done, added what tools were used, providing link to crate.
</blockquote></details>

Adding link to the crates package might not be good enough. we should the exact version that is used, and unify how we use that tool, so that a simple `make generate` will always result in the same output at any given time.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: 36 of 37 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: 35 of 37 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`src/types/coreum/asset/ft/v1.rs` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-Nebg0Qm3Hu7pwKTyXDh:-Nec48xFCWDcZ4JYIy9h:b-igyyeq) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/7a24ee0febaf3c7ae5ffdc388a3aa5ba5e6da504/src/types/coreum/asset/ft/v1.rs#L2)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Adding link to the crates package might not be good enough. we should the exact version that is used, and unify how we use that tool, so that a simple `make generate` will always result in the same output at any given time.
</blockquote></details>

let's discuss later

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 12 of 12 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @wojtek-coreum, and @ysv)

___
*[`src/types/coreum/asset/nft/v1.rs` line 3 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-Nen1RjBD4MhRHNy47b1:-Nen1RjBD4MhRHNy47b2:b-rpn7k9) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/64e7034b7c9f44613a8d714c600e80c0f90c1f33/src/types/coreum/asset/nft/v1.rs#L3)):*
> ```XML
> use osmosis_std_derive::CosmwasmExt;
> 
> // These proto structures were generated using protoc-gen-rust (for more information visit https://crates.io/crates/protobuf-codegen), adding derive macros afterwards.
> ```

can you make our generator and this line of comment, so you don't have to do it ?

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`src/types/coreum/asset/nft/v1.rs` line 3 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-Nen1RjBD4MhRHNy47b1:-Nen3vc-5e9-y_1HJweN:b-34ex0w) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/64e7034b7c9f44613a8d714c600e80c0f90c1f33/src/types/coreum/asset/nft/v1.rs#L3)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

can you make our generator and this line of comment, so you don't have to do it ?
</blockquote></details>

It does, our generator generates everything you see in this file.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`src/types/coreum/asset/nft/v1.rs` line 3 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8#-Nen1RjBD4MhRHNy47b1:-Nen4IDX-4nVFuR1lakX:b1xtufu) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/64e7034b7c9f44613a8d714c600e80c0f90c1f33/src/types/coreum/asset/nft/v1.rs#L3)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

It does, our generator generates everything you see in this file.
</blockquote></details>

It comes directly from https://github.com/CoreumFoundation/coreum/blob/master/proto/coreum/asset/nft/v1/nft.proto

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Pull request merged**
