### PR TITLE
Publish crate

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`.github/workflows/release.yml` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2#-NU6Us-O3Sj3ZwxSRpqt:-NU6Us-P--ab2ciHaO24:b-pr49xz) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/178125ae4444e73c16507b5ea50baa08d86aa5c8/.github/workflows/release.yml#L1)):*
> ```YAML
> name: release
> ```

have you succeeded running it because I see failure here 

https://github.com/CoreumFoundation/coreum-wasm-sdk/actions/runs/4818067353/jobs/8579561097

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/release.yml` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2#-NU6Us-O3Sj3ZwxSRpqt:-NU6VMXJ7R6qv3f9XgWq:b-5o9v9r) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/178125ae4444e73c16507b5ea50baa08d86aa5c8/.github/workflows/release.yml#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

have you succeeded running it because I see failure here 

https://github.com/CoreumFoundation/coreum-wasm-sdk/actions/runs/4818067353/jobs/8579561097
</blockquote></details>

And error perfectly says what is wrong:
```
It seems package 'coreum-wasm-sdk' modified since '0.1.0' so new version should be published
```

It means that we updated files in repo without bumping the version. This check might be disabled but I think it's fine to have it.
I tested it only with "dry-run" to not create fake releases. Once reviewed, we should test with new version.

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`.github/workflows/release.yml` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2#-NU6Us-O3Sj3ZwxSRpqt:-NU6ZzznAjtHUUF0m8xo:b-kv4gig) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/178125ae4444e73c16507b5ea50baa08d86aa5c8/.github/workflows/release.yml#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

And error perfectly says what is wrong:
```
It seems package 'coreum-wasm-sdk' modified since '0.1.0' so new version should be published
```

It means that we updated files in repo without bumping the version. This check might be disabled but I think it's fine to have it.
I tested it only with "dry-run" to not create fake releases. Once reviewed, we should test with new version.
</blockquote></details>

ok
I suggest to release a new version (probably v0.1.1) after we merge this, right ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/release.yml` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2#-NU6Us-O3Sj3ZwxSRpqt:-NU6_zG_92rxZyeU_Ij2:b2nign6) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/178125ae4444e73c16507b5ea50baa08d86aa5c8/.github/workflows/release.yml#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
I suggest to release a new version (probably v0.1.1) after we merge this, right ?
</blockquote></details>

yes

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Pull request merged**
