### PR TITLE
Upgrade msg and version field

### PR DESCRIPTION
**Pull request by keyleu**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/5)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/5)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @keyleu and @miladz68)

___
*[`src/assetft.rs` line 118 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/5#-NYrgSKR6pgRuwLDKpCI:-NYrgSKR6pgRuwLDKpCJ:b-q0ovsm) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/85a85c4c020cdefc5ef986e609871d14f83d0090/src/assetft.rs#L118)):*
> ```XML
>         coin: Coin,
>     },
>     UpgradeTokenV1 {
> ```

Blocked until test pass.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Pull request merged**
