### PR TITLE
Update cosm WASM sdk with latest proto

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/17)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/17)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/17)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil)

___
*[`src/shim.rs` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/17#-OCXy3_20SQmypIm81P-:-OCXy3_20SQmypIm81P0:bxi2tfi) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/845a70f437e97d37578e699ff9c780a01c7193fc/src/shim.rs#L84)):*
> ```XML
> }
> 
> #[derive(Clone, Copy, PartialEq, Eq, ::prost::Message, schemars::JsonSchema)]
> ```

Do you remember I mentioned this `Copy` trait implementation and the problem with `Option<>` fields?
Did you make sure that it doesn't make any problem?
___
*[`src/types/coreum/dex/v1.rs` line 495 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/17#-OCXyekxEJAVPI3a4tUa:-OCXyekxEJAVPI3a4tUb:bjmj7mq) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/845a70f437e97d37578e699ff9c780a01c7193fc/src/types/coreum/dex/v1.rs#L495)):*
> ```XML
>     pub orders: ::prost::alloc::vec::Vec<Order>,
>     /// order_sequence is current order sequence;
>     #[prost(uint64, tag = "4")]
> ```

Isn't this a breaking change to the proto? I believe we should prevent these from happening

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/17)* status: all files reviewed, 2 unresolved discussions

___
*[`src/shim.rs` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/17#-OCXy3_20SQmypIm81P-:-OCYAiH_BbEPw4mu4sUT:bgexkwp) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/845a70f437e97d37578e699ff9c780a01c7193fc/src/shim.rs#L84)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Do you remember I mentioned this `Copy` trait implementation and the problem with `Option<>` fields?
Did you make sure that it doesn't make any problem?
</blockquote></details>

The tests pass, so I expect that's the answer. It works.
___
*[`src/types/coreum/dex/v1.rs` line 495 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/17#-OCXyekxEJAVPI3a4tUa:-OCYAsstB3VGmOXn7RhU:ba39b8m) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/845a70f437e97d37578e699ff9c780a01c7193fc/src/types/coreum/dex/v1.rs#L495)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Isn't this a breaking change to the proto? I believe we should prevent these from happening
</blockquote></details>

It's expected breaking change. Genesis it a template to start from the current state in case of export of it. What is regarding other parts, the  breaking change is DEX only, which is not released, so we can change it until release.

**Comment by masihyeganeh** [comment]
*[`src/shim.rs` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/17#-OCXy3_20SQmypIm81P-:-OCYF86I6_qc2GhrExuT:bhki2s9) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/845a70f437e97d37578e699ff9c780a01c7193fc/src/shim.rs#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The tests pass, so I expect that's the answer. It works.
</blockquote></details>

This project doesn't have any tests, but please make sure it doesn't break other projects

**Pull request merged**
