### PR TITLE
Changed derives to cw_serde, query responses and added all possible queries/messages

### PR DESCRIPTION
**Pull request by keyleu**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`src/nft.rs` line 88 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXu3-uXDxWuSLqI7vxI:-NXuJpC_EGoqsdkYMk9T:b-fbk6z4) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/2215ccde122c6d241f25f623225a014f8b5cfd26/src/nft.rs#L88)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Have you tested the NFTs query in the contract?
</blockquote></details>

this is an excellent point, let's modify our integration tests to make sure all the newly added queries work.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`src/nft.rs` line 88 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXu3-uXDxWuSLqI7vxI:-NXuRTp41aPqI2rmo-S3:b-vdqx83) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/2215ccde122c6d241f25f623225a014f8b5cfd26/src/nft.rs#L88)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this is an excellent point, let's modify our integration tests to make sure all the newly added queries work.
</blockquote></details>

Yes, that is what I'm working on now at the moment, I'm modifying all the integration tests to take into account all new queries and messages

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`src/nft.rs` line 88 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXu3-uXDxWuSLqI7vxI:-NXxdiZdDFsolDIlDUn4:bdfw3cz) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/2215ccde122c6d241f25f623225a014f8b5cfd26/src/nft.rs#L88)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Yes, that is what I'm working on now at the moment, I'm modifying all the integration tests to take into account all new queries and messages
</blockquote></details>

Becase as far as I remeber the `NFTs` isn't supported by the query handler.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @wojtek-coreum, and @ysv)

___
*[`Cargo.toml` line 13 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXy7oZ4AG4hjpx8S_Nq:-NXy7oZ4AG4hjpx8S_Nr:bdzvqu8) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/ad58f8846464db75e0dfc99f27493381dcc260fb/Cargo.toml#L13)):*
> ```TOML
> serde = { version = "1.0.164", default-features = false, features = ["derive"] }
> schemars = "0.8.12"
> cosmwasm-schema = "1.2.6"
> ```

there should an empty line at the end of the file. you see that github is complaining with a red marker.

**Review by miladz68 — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @wojtek-coreum, and @ysv)

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`Cargo.toml` line 13 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXy7oZ4AG4hjpx8S_Nq:-NXzy0NGBux8CHfAOR9z:b2m85og) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/ad58f8846464db75e0dfc99f27493381dcc260fb/Cargo.toml#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

there should an empty line at the end of the file. you see that github is complaining with a red marker. 
</blockquote></details>

I'm surprised github is complaining about this, the package works. I'll add one anyways
___
*[`src/nft.rs` line 88 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXu3-uXDxWuSLqI7vxI:-NXzxx835Gkk-a1z8lZ7:b-f26dc7) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/2215ccde122c6d241f25f623225a014f8b5cfd26/src/nft.rs#L88)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Becase as far as I remeber the `NFTs` isn't supported by the query handler. 
</blockquote></details>

I actually removed all extra NFTs queries because Milad told me this module is getting deprecated soon, so I left the ones that were there already

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`src/nft.rs` line 88 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXu3-uXDxWuSLqI7vxI:-NY2ykwr0AS2QLOl-9tG:b-tagkm7) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/2215ccde122c6d241f25f623225a014f8b5cfd26/src/nft.rs#L88)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get you reply. @miladz68 What do you mean by depricated?
</blockquote></details>

you guys are talking about different stuff. Basically, both Dima and I want to see that the queries that are being added in this PR, are tested via integration tests. Fr that Keyne has made a separate PR in coreum.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`src/nft.rs` line 88 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXu3-uXDxWuSLqI7vxI:-NY359t7AX--k7mnMl90:bd2346v) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/2215ccde122c6d241f25f623225a014f8b5cfd26/src/nft.rs#L88)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you guys are talking about different stuff. Basically, both Dima and I want to see that the queries that are being added in this PR, are tested via integration tests. Fr that Keyne has made a separate PR in coreum. 
</blockquote></details>

Correct, everything added in the SDK here is successfully tested in the other PR with integration tests

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`src/nft.rs` line 88 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXu3-uXDxWuSLqI7vxI:-NY3CiMe8RmBMTXSONhs:b4cjwz4) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/2215ccde122c6d241f25f623225a014f8b5cfd26/src/nft.rs#L88)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Correct, everything added in the SDK here is successfully tested in the other PR with integration tests
</blockquote></details>

My point here is that if there are queries in the coreum they should be here as well. For both NFT and Asset/NFT.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`src/nft.rs` line 88 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXu3-uXDxWuSLqI7vxI:-NY4AJjg6VFzZSggf0FZ:biw1ays) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/2215ccde122c6d241f25f623225a014f8b5cfd26/src/nft.rs#L88)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

My point here is that if there are queries in the coreum they should be here as well. For both NFT and Asset/NFT. 
</blockquote></details>

Like discussed in meeting, will add NFT as well

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`src/nft.rs` line 88 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4#-NXu3-uXDxWuSLqI7vxI:-NYHqlf26QGCmuDYE_WD:bkciw4s) ([raw file](https://github.com/CoreumFoundation/coreum-wasm-sdk/blob/2215ccde122c6d241f25f623225a014f8b5cfd26/src/nft.rs#L88)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, let's wait. Alos check and if there are more queries and them as well please.
</blockquote></details>

Ok added all queries to the package. I also tested them with integration tests so format is correct. Now we have all possible queries for all modules

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum-wasm-sdk/4)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
